
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty
#relative_permalinks: true

language-label:
  de:                Read in english
  en:                Auf deutsch lesen
# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         site name
by:
  de:                Von
  en:                By
title:
  de:                Ein Tagebuch f체r unsere Reise durch S체dostasien
  en:                A travel journal for our Southeast Asia travels
subscribe_title:
  de:                Bleib in Verbindung
  en:                Stay in touch
subscribe:
  de:                Hat dir dieser Beitrag gefallen? Lass dich per Email 체ber neue Beitr채ge benachrichtigen.
  en:                Did you enjoy reading this? Sign up for email notifications when we publish new blog posts.
subscribe_email:
  de:                Deine Email-Adresse
  en:                Your email address
subscribe_button:
  de:                Benachrichtigung per Email
  en:                Get notified by email
tagline:             'A travel journal for our Southeast Asia travels'
description:         ''
url:                 'http://www.wirsindreisen.de'
rss:                 rss feed url
baseurl:             '/blog'
baseurl_posts_img:   '/blog/assets/images/posts/'
baseurl_posts_img_thumbnail: '/blog/assets/images/posts/thumbnail/'
baseurl_featured_img: '/blog/assets/images/hero/'
baseurl_featured_thumbnail: '/blog/assets/images/thumbnail/'
baseurl_javascripts: '/blog/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              ina-jonas # get it on https://disqus.com/admin/

author:
  name:           	 Jonas
  url:            	 your site url
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
