
baseurl:             ''
baseurl_posts_img:   '/assets/images/posts/'
baseurl_posts_img_thumbnail: '/assets/images/posts/thumbnail/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
